services:
  cfs-app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    environment:
      - JDBC_ROOT=root
      - JDBC_PASSWORD=root
      - JDBC_URL=jdbc:mysql://mysql:3306/file_storage
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis-password
      - MINIO_URL=http://s3:9000
      - MINIO_USER=minio-user
      - MINIO_PASSWORD=password
    networks:
      - nginx-net
    restart: on-failure:5
    depends_on:
      - mysql
      - s3
      - redis
    command: [ "java", "-jar", "/usr/app/build/libs/cloud-file-storage.jar" ]
  mysql:
    container_name: mysql-container
    image: mysql:8
    volumes:
      - /srv/cfs/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: file_storage
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
      - 33060
    networks:
      - nginx-net
  s3:
    container_name: minio-container
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: password
    expose:
      - 9000
    volumes:
      - /srv/cfs/minio:/data
    networks:
      - nginx-net
    command: server /data --console-address ":9001"
  redis:
    container_name: redis-container
    image: redis:latest
    environment:
      REDIS_PASSWORD: redis-password
      REDIS_USER: redis-user
      REDIS_USER_PASSWORD: redis-user-password
    expose:
      - 6379
    volumes:
      - /srv/cfs/redis:/data
    networks:
      - nginx-net
networks:
  nginx-net:
    external: true
