services:
  mysql:
    container_name: mysql-container
    image: mysql:8
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: file_storage
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  s3:
    container_name: file-storage-minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /home/minio:/data
    command: server /data --console-address ":9001"

volumes:
  mysql_volume:
    driver: local
  minio:
    driver: local
