services:
  mysql:
    container_name: mysql-container
    image: mysql:8
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: file_storage
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - internal_network
  s3:
    container_name: file-storage-minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    expose:
      - 9000
    volumes:
      - /home/minio:/data
    networks:
      - internal_network
    command: server /data --console-address ":9001"
  redis:
    container_name: redis_container
    image: redis:latest
    environment:
      REDIS_PASSWORD: redis-password
      REDIS_USER: redis-user
      REDIS_USER_PASSWORD: redis-user-password
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - ./redisdata:/data
    networks:
      - internal_network
volumes:
  mysql_volume:
    driver: local
  minio:
    driver: local
networks:
  internal_network:
    driver: bridge