services:
  cfs-app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    env_file:
      - prod.env
    networks:
      - nginx-net
    restart: on-failure:5
    depends_on:
      - mysql
      - s3
      - redis
    command: [ "java", "-jar", "/usr/app/build/libs/cloud-file-storage.jar" ]
  mysql:
    container_name: mysql-container
    image: mysql:8
    volumes:
      - /srv/cfs/mysql:/var/lib/mysql
    env_file:
      - prod.env
    expose:
      - 3306
      - 33060
    networks:
      - nginx-net
  s3:
    container_name: minio-container
    image: minio/minio:latest
    env_file:
      - prod.env
    expose:
      - 9000
    volumes:
      - /srv/cfs/minio:/data
    networks:
      - nginx-net
    command: server /data --console-address ":9001"
  redis:
    container_name: redis-container
    image: redis:latest
    env_file:
      - prod.env
    expose:
      - 6379
    volumes:
      - /srv/cfs/redis:/data
    networks:
      - nginx-net
networks:
  nginx-net:
    external: true
