spring:
  datasource:
    username: "root"
    password: "root"
    url: jdbc:mysql://localhost:3306/file_storage
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: redis-password