spring:
  application:
    name: cloud-file-storage
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_FILE_SIZE:10MB}
server:
  port: ${PORT:8080}
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    max-swallow-size: -1
logging:
  level:
    org:
      springframework:
        web: INFO
    ROOT: INFO

minio:
  endpoint: ${MINIO_URL:http://127.0.0.1:9000}
  user: ${MINIO_USER:minio-user}
  password: ${MINIO_PASSWORD:password}

app:
  bucket: "user-files"
