name: Deploy
on:
  push:
    branches: ["master"]
jobs:
  deploy:
    runs-on: self-hosted
    env:
      JDBC_PASSWORD: root
      REDIS_PASSWORD: redis-password
      MINIO_ROOT_PASSWORD: password
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: docker-compose
        run: make deploy

